buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:8.1.0")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.24")
        classpath("org.jetbrains.kotlin:kotlin-serialization:1.9.24")
        classpath("com.karumi:shot:5.13.0")
    }
}

plugins {
    alias(libs.plugins.test.aggregation.coverage)
    alias(libs.plugins.detekt)
    alias(libs.plugins.hilt) apply false
}



task("clean") {
    delete(rootProject.layout.buildDirectory)
}

testAggregation {
    modules {
        exclude(project(":shared-testing"))
        exclude(project(":app"))     // Temporarily exclude app module due to Hilt compatibility issue
    }
    coverage {
        exclude(
            listOf(
                "**/R.class",
                "**/R\$*.class",
                "**/BuildConfig.*",
                "**/Manifest*.*",
                "**/*Module.*", // Modules for Hilt.
                "**/*Hilt*.*,", // Hilt auto-generated code.
                "**/Hilt_*.*,", // Hilt auto-generated code.
                "**/_HiltComponents_*.*,", // Hilt auto-generated code.
                "**/_HiltComponents.*.*,", // Hilt auto-generated code.
                "**/Hilt_*.*,", // Hilt auto-generated code.
                "**/*_GeneratedInjector.*,", // Hilt auto-generated code.
                "**/*InjectInterface.*,", // Hilt auto-generated code.
                "**/hilt_aggregated_deps/*,", // Hilt auto-generated code.
                "**/*hilt_aggregated_deps*",
                "**/*MembersInjector*.*", // Hilt auto-generated code.
                "**/*_Provide*Factory*.*",
                "**/*_Factory.*", //Hilt auto-generated code
                "**/*_Factory.InstanceHolder.*", //Hilt auto-generated code
                "**/codegen/*.*", //Hilt auto-generated code
                "**/*\$*\$*.*", // Anonymous classes generated by kotlin
                "**/*Directions.*", // Nav args generated code
                //add libraries
                "android/**/*.*",
                "androidx/**/*.*",
                "io/**/*.*",
                //remove what we don't test
                "androidTest/**/*.*",
                "test/**/*.*",
                "**/prieto/fernando/spacex/theme/**",
                "**/prieto/fernando/spacex/presentation/screens/**",
                "**/prieto/fernando/spacex/",
                "**/prieto/fernando/spacex/presentation/navigation/"
            )
        )
    }
}
