buildscript {
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:8.1.0")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.22")
        classpath("com.karumi:shot:5.13.0")
    }
}

plugins {
    id("io.github.gmazzo.test.aggregation.coverage") version "2.4.4"
    id("io.gitlab.arturbosch.detekt") version "1.22.0"
    id("com.google.dagger.hilt.android") version "2.47" apply false
}

allprojects {
    // Set Java toolchain to JDK 17 for all projects
    tasks.withType<JavaCompile> {
        sourceCompatibility = "17"
        targetCompatibility = "17"
    }
    
    tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
        kotlinOptions {
            jvmTarget = "17"
        }
    }

    repositories {
        google()
        jcenter()
        maven("https://oss.sonatype.org/content/repositories/snapshots/")
        mavenCentral()
    }
}

task("clean") {
    delete(rootProject.buildDir)
}



testAggregation {
    modules {
        exclude(project(":core-kotlin-test"))
    }
    coverage {
        exclude(
            listOf(
                "**/R.class",
                "**/R$*.class",
                "**/BuildConfig.*",
                "**/Manifest*.*",
                "**/*Module.*", // Modules for Hilt.
                "**/*Hilt*.*,", // Hilt auto-generated code.
                "**/Hilt_*.*,", // Hilt auto-generated code.
                "**/_HiltComponents_*.*,", // Hilt auto-generated code.
                "**/_HiltComponents.*.*,", // Hilt auto-generated code.
                "**/Hilt_*.*,", // Hilt auto-generated code.
                "**/*_GeneratedInjector.*,", // Hilt auto-generated code.
                "**/*InjectInterface.*,", // Hilt auto-generated code.
                "**/hilt_aggregated_deps/*,", // Hilt auto-generated code.
                "**/*hilt_aggregated_deps*",
                "**/*MembersInjector*.*", // Hilt auto-generated code.
                "**/*_Provide*Factory*.*",
                "**/*_Factory.*", //Hilt auto-generated code
                "**/*_Factory.InstanceHolder.*", //Hilt auto-generated code
                "**/codegen/*.*", //Hilt auto-generated code
                "**/*$*$*.*", // Anonymous classes generated by kotlin
                "**/*Directions.*", // Nav args generated code
                //add libraries
                "android/**/*.*",
                "androidx/**/*.*",
                "io/**/*.*",
                //remove what we don't test
                "androidTest/**/*.*",
                "test/**/*.*",
                "**/prieto/fernando/spacex/theme/**",
                "**/prieto/fernando/spacex/presentation/screens/**",
                "**/prieto/fernando/spacex/",
                "**/prieto/fernando/spacex/presentation/navigation/"
            )
        )
    }
}
