package prieto.fernando.dependencies

object Versions {
    const val core = "1.3.2"
    const val fragment = "1.2.5"
    const val navigation = "2.3.2"
    const val compose = "1.2.1"
    const val composeSystemUi = "0.21.3-beta"
    const val composeViewModel = "2.5.1"
    const val composeNavigation = "2.5.1"
    const val constraintLayout = "2.0.4"
    const val legacySupportV4 = "1.0.0"
    const val lifecycleLivedataKtx = "2.2.0"
    const val livedataTesting = "1.1.1"
    const val dagger = "2.24"
    const val hiltJetpack = "1.0.0"
    const val hilt = "2.44"
    const val hiltVM = "1.0.0-alpha03"
    const val hiltTest = "2.37"
    const val androidxTest = "1.4.0"
    const val espresso = "3.4.0"
    const val androidxJunit = "1.1.1"
    const val junit = "4.13.1"
    const val junitPlatformRunner = "1.0.2"
    const val mockk = "1.12.2"
    const val gradle = "7.1.0"
    const val kotlin = "1.5.31"
    const val timber = "4.7.1"
    const val lottie = "4.2.0"
    const val lottieCompose = "4.2.1"
    const val coreTesting = "2.1.0" // 2.1.0 Doesn't find TaskExecutorRule
    const val retrofit = "2.6.2"
    const val retrofitConverterGson = "2.4.0"
    const val okhttpLoggingInterceptor = "4.9.1"
    const val coil = "1.4.0"
    const val jodaTime = "2.10.8"
    const val ktlint = "0.43.1"
    const val mockWebServer = "4.9.0"
    const val browser = "1.0.0"
    const val kotlinxCoroutines = "1.6.4"
}